runtimes/react-native/react-native.mdx

The links are not pointing to anything, making the experience annoying. Is it on purpose or a mistake?

fix(runtimes): update external react-native github links

---

runtimes/web/low-level-api-usage.mdx

This PR also replaces references to webgl, in favor of webgl2. 
Manually upgrading the links to `2.26.1` is a quick fix, but in the future we should add auto-updating to the github workflows.

Update webgl2 and unkg references to use 2.26.1

---

editor/data-binding/overview.mdx

Follows on from PR comments in #57. All should be addressed. Still welcoming general review and critique.
- Add consistency by always referring to engineers as developers
- Link to view model instances from view models
- Add information about instances at runtime
- Removed references to supporting inputs and events for some time
- Added coverage for events used internal to the Rive file, and extra clarification of feature coverage
- Fixed event property comparison to be keyable rather than fixed, and add nesting gotcha
- Added audio limitation to data binding
- Added a section about nesting use cases better served by data binding

fix(data binding): Address a number of PR comments

---

editor/animate-mode/animate-mode-overview.mdx
editor/constraints/constraints-overview.mdx
editor/data-binding/overview.mdx
editor/events/overview.mdx
editor/fundamentals/overview.mdx
editor/interface-overview/overview.mdx
editor/layouts/layouts-overview.mdx
editor/manipulating-shapes/manipulating-shapes.mdx
editor/share-links/overview.mdx
editor/state-machine/state-machine.mdx
editor/text/text-overview.mdx
game-runtimes/bevy/bevy.mdx
runtimes/choose-a-renderer/overview.mdx

- Updates editor overview pages to follow the format:
- Title: Topic Overview
- Sidebar title: Overview
- Updates Bevy root page title from Overview to Bevy to follow other game runtimes
The new titles _should_ be used when the docs are crawled. This should update, for example, Data Binding overview from "Overview" to "Data Binding - Overview", while showing "Overview" in the sidebar still.

docs: update overview (sidebar) titles

---

game-runtimes/unity/runtime-asset-swapping.mdx

This PR adds docs about a new File.Load overload that lets users fall back to assets assigned in the inspector when using the AssetLoaderCallback.

docs(unity): add fallbackToAssignedAssets overload

---

game-runtimes/unity/state-machines.mdx

This PR updates the state machine docs to encourage waiting for the Rive Widget to load before accessing the state machine.

docs(unity): update state machine example to wait for widget load

---

runtimes/loading-assets.mdx

Updates the old React Native example link for out-of-band assets with the updated URL.

fix(app-runtimes): update react native out-of-band example link

---

game-runtimes/unity/unity.mdx

This PR updates the docs to mention the minimum version of Unity supported by the Rive Unity package.

docs(unity): add min unity version support

---

docs.json
editor/constraints/scroll-constraint.mdx

This PR adds 2 updates:
- Reorganizes the main sections under Editor.  Moves Text up near the other core tools and object types. Moves Layout up so that the "in Editor tools" are grouped more closely together.
- Added a Scroll Constraints page for completeness, but its just a landing page which links to Layouts & Scrolling pages.

docs(editor): reorganize editor sections & add Scroll Constraint page

---

snippets/features-support.mdx

As requested by Guido, add a link to runtime docs as well.

docs(feature-support): Add link to data binding runtimes

---

editor/share-links/overview.mdx
runtimes/choose-a-renderer/overview.mdx
runtimes/flutter/rive-native.mdx
runtimes/react-native/migration-guide.mdx
snippets/features-support.mdx

Updates feature naming and adds links out to the Vector Feathering page (not hosted on docs).

refactor(feature-support): use Vector Feathering feature naming

---

runtimes/data-binding.mdx
snippets/features-support.mdx

This PR adds docs for the new databinding hooks in the React package. It also updates the feature support page to mention the supported version for databinding.

docs(react): add databinding docs

---

runtimes/web/rive-parameters.mdx

https://github.com/rive-app/rive-wasm/blob/master/js/src/rive.ts#L1351

docs(web): updated RiveParameters `file` to `riveFile`

---

editor/data-binding/lists.mdx
editor/mcp/integration.mdx
snippets/early-access-feature.mdx
snippets/early-access.mdx

- Adds usage of new EarlyAccess snippet to MCP Integration

docs: split early access and early access feature into separate snippets

---

editor/mcp/integration.mdx

The Rive MCP server will be unavailable if the app is not opened; this should help users troubleshoot if the server is not available / visible.

docs(mcp): add note about requiring ea to be open

---

runtimes/web/low-level-api-usage.mdx

Typo: `...the renderer to `flush()` to empty different....`
resolves: #120

fix: typo when referring to webgl2-advanced flush

---

runtimes/data-binding.mdx

1. Update the table to use the correct color formatting: 
2. Add more examples to the JS mutable properties section
3. Sorry, a lot of linting garbage in here. :( 
resolves: https://github.com/rive-app/rive-docs/issues/153

chore: add more info about colors to JS data binding

---

snippets/features-support.mdx

This adds caching a .riv to the feature support docs. This seems like an old feature and I'm having a hard time finding when it first got supported in each runtime so I didn't include a version. 
resolves #45

chore: add caching to feature support page

---

docs.json
runtimes/animation-playback.mdx
runtimes/artboards.mdx
runtimes/caching-a-rive-file.mdx
runtimes/flutter/flutter.mdx
runtimes/flutter/migration-guide.mdx
runtimes/flutter/rive-native.mdx
runtimes/inputs.mdx
runtimes/layout.mdx
runtimes/loading-assets.mdx
runtimes/rive-events.mdx
runtimes/state-machines.mdx
runtimes/text.mdx
snippets/runtimes/animation-control-and-interaction.mdx

- Rewrite the Flutter documentation to support the new Flutter API for version 0.14.0 (major release)
- Significant changes in how you use Rive Flutter 
- Migration Guide
- Removes legacy examples

docs(flutter): documentation for v0.14.0 release

---

getting-started/best-practices.mdx
runtimes/layout.mdx
runtimes/loading-assets.mdx
runtimes/react/react.mdx
runtimes/rive-events.mdx

We're converting all the demos to Typescript. This PR updates the links to make sure the right .tsx file is open.

Update codesandbox links to include file name

---

getting-started/best-practices.mdx
runtimes/caching-a-rive-file.mdx
runtimes/data-binding.mdx
runtimes/flutter/alternative-widget-setup.mdx
runtimes/layout.mdx
runtimes/loading-assets.mdx
runtimes/react/react.mdx
runtimes/web/canvas-vs-webgl.mdx
runtimes/web/low-level-api-usage.mdx
runtimes/web/web-js.mdx

When this merges
- All Web and React examples are now using Typescript
- All Web and React examples specify which file to open (the .ts or .tsx with the Rive file)
Other stuff:
- Fix from yesterday's PR: I accidentally names some non-React files to .tsx, when they should have been .ts. 
- Remove the Centaur example
This does not include legacy examples (inputs, text, etc.), which we probably won't update.

docs(web): update codesandbox to typescript

---

game-runtimes/unity/unity.mdx

This PR updates the Unity docs to mention Vulkan support on Windows, Linux, and Android.

docs(unity): include vulkan support

---

runtimes/data-binding.mdx

Updates incorrect documentation regarding updating image properties in the Apple runtime. Additionally, the usage sections for each property type include both auto binding and manual binding, since that usage may be overlooked from an above section.

docs(apple): update image property usage + fetching an instance

---

game-runtimes/unity/runtime-asset-swapping.mdx
runtimes/data-binding.mdx

This PR updates the Unity docs to link to demos that showcase how to swap images at runtime.

docs(unity): link to image swapping and databinding demos

---

runtimes/flutter/migration-guide.mdx

version '0.14.0' is currently not available, so it needed to be changed to '0.14.0-dev.8'

Update migration-guide.mdx to include the latest working version of flutter

---

snippets/demos.jsx

Mintlify won't let you upload .riv files to their s3. This PR switches to ours. 
Previews: 
- Demos: https://rive-replace-rivs.mintlify.app/runtimes/caching-a-rive-file
- https://rive-replace-rivs.mintlify.app/runtimes/layout

Link to s3 .rivs

---

docs.json
game-runtimes/unity/data-binding.mdx
game-runtimes/unity/fundamentals.mdx
game-runtimes/unity/inputs.mdx
game-runtimes/unity/layouts.mdx
game-runtimes/unity/listeners.mdx
game-runtimes/unity/rive-events.mdx
game-runtimes/unity/state-machines.mdx
game-runtimes/unity/text.mdx
snippets/unity/legacy-api-notice.mdx
snippets/unity/legacy-databinding-notice.mdx

This PR updates mentions of the 'low-level API' in the Unity docs to say 'legacy API' instead. It also moves features like inputs and events to a 'Legacy' section in the Unity docs.

docs(unity): change change low-level API to legacy API

---

custom.css

Mintlify added `height: 100%` to all `iframe`'s. This overrides YouTube's default height. This makes some of our videos look squished (left), others disappear: 
This'll fix it while we're waiting for Mintlify to undo what they did.

Override Mintlify's new default iframe height
